# Generated by Django 5.0.1 on 2024-03-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('inventory_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invetory_quantity', models.IntegerField()),
                ('date_entry', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.SmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
            ],
        ),
        migrations.CreateModel(
            name='Inventories_sales',
            fields=[
                ('inventory_sales_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.inventories')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sales')),
            ],
        ),
    ]
