# Generated by Django 5.0.1 on 2024-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='inventory_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventories_sales',
            name='inventory_sales_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
