# Generated by Django 5.0.1 on 2024-03-11 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('inventory_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invetory_quantity', models.IntegerField()),
                ('date_entry', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
            ],
        ),
        migrations.CreateModel(
            name='Inventories_sales',
            fields=[
                ('inventory_sales_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.inventories')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sales')),
            ],
        ),
    ]
