# Generated by Django 5.0.1 on 2024-03-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_inventories_inventory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='invetory_quantity',
            new_name='inventory_quantity',
        ),
    ]
